// This file is generated by Terraform
// Environment-specific configuration

const CONFIG = {
    environment: "production",
    difficulty: "hard",
    startingResources: {
        wood: 3,
        stone: 2,
        food: 1
    },
    gameSettings: {
        hungerDecayRate: 3,
        thirstDecayRate: 4,
        energyDecayRate: 2,
        resourceMultiplier: 0.8,
        dangerLevel: 0.5
    },
    features: {
        craftingEnabled: true,
        weatherEvents: true,
        randomEvents: true
    },
    deploymentInfo: {
        version: "1.0.0",
        deployedBy: "terraform",
        timestamp: new Date().toISOString()
    }
};

// Export for use in game
window.GAME_CONFIG = CONFIG;
